version: "3"
services:
#  Here it automatically makes the bridge between the two containers, so is not necessary to create it
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDB
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db